name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Jest Test
      id: jest-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Jest Test
        setup-command: npm install
        command: npx vitest
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JEST-TEST_RESULTS: "${{steps.jest-test.outputs.result}}"
      with:
        runners: jest-test
